GenomelEditor/urls.py
from django.urls import path

from . import views

app_name= 'GenomelEditor'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout', views.logout_user, name='logout'),
    path('login', views.login_user, name='login'),
    path('annotate', views.annotate, name='annotate'),
    path('save_annotation', views.save_annotation, name='save_annotation'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('help', views.help, name='help'),
    path('upload_chants', views.upload_chants, name='upload_chants'),
    path('upload_sources', views.upload_sources, name='upload_sources'),
]

genomel_editor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("genomel_editor/admin/", admin.site.urls),
    path("genomel_editor/", include('GenomelEditor.urls'), name='GenomelEditor'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/admin_dashboard.html
{% extends "base.html" %}

{% block page %}
    {% if user.is_superuser %}


    <h1>Admin dashboard</h1>

    <h2>Upload chants CSV</h2>
    <form action="{% url "GenomelEditor:upload_chants" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="chants_csv" placeholder="Chants CSV">
        <input type="submit" value="Upload">
    </form>

    <h2>Upload sources CSV</h2>
    <form action="{% url "GenomelEditor:upload_sources" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="sources_csv" placeholder="Sources CSV">
        <input type="submit" value="Upload">
    </form>

    {% else %}
        <h1>Not authorized.</h1>
    {% endif %}
{% endblock %}

templates/annotate.html
{% extends "base.html" %}
{% block page %}

    {% include "chant_description.html" with chant=chant %}
    <br>
    {% include "image_display.html" with melody=melody chant=chant %}
    <br>
    {# Have to pass both melody and chant to the transcription because of the form #}
    {# action having to send the data upstream to really create a new melody. #}
    {% include "volpiano_transcription.html" with melody=melody chant=chant %}

{% endblock %}

templates/annotator_dashboard.html
<div id="annotator_dashboard">
    <span class="annotator_dashboard_heading"><h2>Annotator dashboard</h2></span>
    {% for name, melody_count in sorted_annotator_stats %}
        <div class="annotator_stat" id="annotator_stat_{{ name }}">
            <span class="annotator_stat_name">{{ name }}:</span>
            <span class="annotator_stat_value">{{ melody_count }}</span>
        </div>
    {% endfor %}

</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genome of Melody Editor</title>
    <link type="text/css" rel="stylesheet" href="{% static 'base.css' %}">
    <link type="image/png" rel="shortcut icon"  href="{% static 'favicon-32x32.png' %}" >
</head>
<body id="body">

    <div id="header">
        {% block header %}
            <h1 id="main_heading">Genome of Melody Editor</h1>

            <!-- Home -->
            <button class="navigation_button">
                <a class="navigation_button_link" href="{% url 'GenomelEditor:index' %}">Home</a>
            </button>
            {% if user.is_authenticated %}
                <!-- Annotate! -->
                <button class="navigation_button">
                    <span><a class="navigation_button_link" href="{% url 'GenomelEditor:annotate' %}">Annotate</a></span>
                </button>

                {% if user.is_superuser %}
                <!-- Annotation admin: uploading data, looking at annotator stats, etc. -->
                <button class="navigation_button">
                    <span><a class="navigation_button_link" href="{% url 'GenomelEditor:admin_dashboard' %}">Admin dashboard</a></span>
                </button>
                {% endif %}
            {% endif %}

            <!-- Help -->
            <button class="navigation_button">
                <span><a class="navigation_button_link" target="_blank" href="{% url 'GenomelEditor:help' %}">Editor Help</a></span>
            </button>

            <!-- Volpiano protocols -->
            <button class="navigation_button">
                <span><a class="navigation_button_link" target="_blank" href="https://cantusdatabase.org/static/documents/2.%20Volpiano%20Protocols.pdf">Volpiano Help</a></span>
            </button>

            <!-- Volpiano checking protocols -- temporary, I will add a more tailor-made document for checkers. -->
            <button class="navigation_button">
                <span><a class="navigation_button_link" target="_blank" href="https://cantusdatabase.org/static/documents/5.%20Volpiano%20Editing%20Guidelines.pdf">Checking Help</a></span>
            </button>

            <!-- Login or logout. -->
            {% if user.is_authenticated %}
                <button class="navigation_button">
                    <span><a class="navigation_button_link" href="{% url 'GenomelEditor:logout' %}">Logout</a></span>
                </button>
                <span style="margin-left: 4pt">Logged in as: <b>{{ user.username }}</b></span>
            {% else %}
                {% include "login.html" %}
            {% endif %}
        {% endblock %}
    </div>

    <div id="page">
        {% block page %}
        {% endblock %}
    </div>

</body>
</html>

templates/chant_description.html
<div id="chant_description">
    <table>
        <tr>
            <td class="chant_description_label_cell"><span class="chant_description_label">Chant ID</span></td>
            <td class="chant_description_value_cell">{{ chant.id }}</td>
        </tr>
        <tr>
            <td class="chant_description_label_cell"><span class="chant_description_label">Cantus ID</span></td>
            <td class="chant_description_value_cell"><a href="https://cantusindex.org/id/{{ chant.cantus_id }}"
                target="_blank"
                rel="noreferrer noopener">{{ chant.cantus_id }}</a>
            </td>
        <tr>
            <td class="chant_description_label_cell"><span class="chant_description_label">Incipit</span></td>
            <td class="chant_description_value_cell">{{ chant.incipit }}</td>
        </tr>
        <tr>
            <td class="chant_description_label_cell"><span class="chant_description_label">Siglum</span></td>
            <td class="chant_description_value_cell">{{ chant.siglum }}</td>
        </tr>
        <tr>
            <td class="chant_description_label_cell"><span class="chant_description_label">Image URL</span></td>
            <td class="chant_description_value_cell"><a href="{{ chant.image_link }}"
                   target="_blank"
                   rel="norefferer noopener">
                {{ chant.image_link }}</a></td>
        </tr>
    </table>
</div>

templates/help.html
{% extends "base.html" %}
{% block page %}
    <p id="help">
        <h1>Annotating with Genomel Editor</h1>
        <p>
            To start annotating with the Genomel Editor, you need to:

            <ul>
                <li>Obtain a user account.
                    (Contact Jan Hajič at the Masaryk Institute and Archives, Czech Academy of Sciences.).
                </li>
                <li>Log in to the editor using the form in the upper area site (header).</li>
                <li>Go to the Annotate page.</li>
                <li>The system will either assign to you a new annotation, or it will
                    load a mellody for you to continue annotating.
                </li>
            </ul>
        </p>
        <p>
            Once you are on the annotation page, you have to 1) load the image,
            2) syllabize the text, 3.1) transcribe the melody into Volpiano, or
            3.2) mark the melody as impossible to transcribe (incomplete or adiastematic),
            and 4) save your progress.
        </p>
        <p>
            1) Loading the image:

            <ul>
                <li>In order to load the image from which you are transcribing,
                    <b>you need to copy the image into the clipboard</b> first.</li>
                <li>Go to the image URL that the system provides you with.
                    Some chant databases serve the image directly to your browser
                    (like ispan.pl). In that case, by right-clicking the image
                    in the browser, a context menu comes up that contains the "Copy Image"
                    option. Click that option.
                </li>
                <li>However, some online libraries, such as Gallica or the British National Library,
                    don't allow you to copy the image directly. However, what they do provide
                    is a download option. If you download the image, it opens in a new browser
                    tab as a normal image file. You can then copy it from there using right-click
                    to bring up the context menu and select "Copy Image".
                </li>
                <li>Once the image is copied, switch back to the annotation tab and
                    <b>just press paste: Ctrl+V (or Cmd+V on Mac).</b> The image will paste
                    itself into the image area.</li>
                <li>The image is draggable, and you can use the buttons to zoom
                    in or out if need be. You can also adjust the size of the image
                    area -- it is resizable using the bottom right corner.</li>
                <li>Once you can comfortably see the part of the image that you
                    should be transcribing, you can start working on the Volpiano
                    transcription.</li>
            </ul>
        </p>

        <p>
            2) Syllabizing the text:

            <ul>
                <li>Under the image, you can see the "Syllabized text" field
                    pre-populated with the manuscript text.</li>
                <li>However, the information we donwloaded from Cantus Index
                    does not contain the syllabization of the text. This has
                    to be done manually (at least if you are the first person
                    to be annotating a chant).</li>
                <li><b>Add hyphens ("-") to indicate syllable breaks.</b> Do not add
                    any spacing.</li>
            </ul>
        </p>

        <p>
            3.1) Transcribing the melody:

            <ul>
                <li>Proceed to transcribe the melody into Volpiano according
                    to the <a  target="_blank" href="https://cantusdatabase.org/static/documents/2.%20Volpiano%20Protocols.pdf">
                        Cantus Volpiano Protocols</a> (clicking the link opens a new tab).</li>
                <li>At any point, to check your progress, click the "Render" button.</li>
            </ul>

            3.2) Marking the melody as impossible to transcribe:

            <ul>
                <li>It can happen that the chant comes from an adiastematic source.
                    In that case, write "1---3" into the Volpiano (which is a valid Volpiano encoding
                    of nothing) and check the "Adiastematic"
                    checkbox.</li>
                <li>In other cases, a chant might be recorded in an incomplete form.
                    This most often happens when the chant occurs in the same source
                    earlier, so possibly only the incipit is written down (so that the
                    singers recall the melody, which they would have known by heart anyway).
                    In this case, do not transcribe anything and check the "Incomplete"
                    checkbox.</li>
            </ul>
        </p>

        <p>
            4) Save your work

            <ul>
                <li>In order to save your work in progress, click the "Save" button.
                    The server should let you continue editing. (We retain the image
                    in the browser's storage, so if you cleared your browsing data since last
                    working on the melody, you will have to copy the image again.)</li>
                <li>Once you are done with the melody transcription and text syllabization,
                    make sure you render your transcription and check that the text
                    and melody fit together properly. Then, to mark the transcription
                    as complete, check the "Is transcribed?" checkbox. Then, click "Save".
                    The melody will be moved to the next step of the process: validation.</li>
            </ul>
        </p>

    </p>

{% endblock %}

templates/image_display.html
{% load static %}

{#<button id="image_paste_from_clipboard">Paste Image</button>#}
<button id="image_zoom_in">Zoom in</button>
<button id="image_zoom_out">Zoom out</button>
<button id="image_zoom_reset">Reset</button>

<div id="image_container"
     style="height: 300px;
            width: 80%;
            background-color: antiquewhite;
            resize: both;
            border: 1px solid goldenrod;
            margin-top: 10px">
    <img id="image"
         src="{% static 'default_image.png' %}"
         alt="test image"
         style="position: relative"/>
</div>

<script>
    // This script loads the image.

    // Either it finds an image for the melody in local storage,
    // or it pastes the image from the clipboard into the image display.

    // In local storage, we refer to the images not by melody ID, but by their
    // chant ID.
    // Each chant only has one melody, and each melody -- even before it is added
    // to the DB -- has a chant. So, we can use the chant ID as the key for the
    // image that we add to local storage for transcribing this melody, possibly before
    // it is added to the database.
    function createImageLocalStorageName(chant_id) {
        return 'GenomelEditor_image_ch-' + chant_id;
    }

    // If the melody does not have an ID yet, it means it has never
    // been annotated before, which means no one could have yet found
    // an image for it. So, only try to load an image if the melody has an ID.
    {% if melody.id %}
        // If the image is in local storage:
        const image_name = createImageLocalStorageName({{ melody.chant.id }});
        const image_as_JSON_string = localStorage.getItem(image_name);
        if (image_as_JSON_string) {
            const image = document.getElementById('image');
            image.src = JSON.parse(image_as_JSON_string);
        }
    {% endif %}

    // For the user:
    // See https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c
    document.onpaste = function(event) {
        const items = (event.clipboardData || event.originalEvent.clipboardData).items;
        // console.log(JSON.stringify(items)); // might give the mime types, but doesn't
        // So far, just testing what data is coming from the paste event.
        for (const index in items) {
            const item = items[index];
            if (item.kind === 'file') {
                var blob = item.getAsFile();
                var reader = new FileReader();
                // The adding the pasted image data into the image element happens
                // in this onload event, which is triggered by reader.readAsDataURL.
                reader.onload = function (event) {
                    // event.target.result contains the base64 code for the image
                    const image = document.getElementById('image');
                    image.src = event.target.result;
                    // console.log(event.target.result); // data url!

                    // Save image to local storage.
                    const new_image_name = createImageLocalStorageName({{ melody.chant.id }});
                    localStorage.setItem(new_image_name, JSON.stringify(event.target.result));
                };
                reader.readAsDataURL(blob);
            }
        }
    }
</script>


<script src="https://unpkg.com/@panzoom/panzoom@4.5.1/dist/panzoom.min.js"></script>
<script>
    // This script adds pan and zoom functionality to the image display after it is loaded..
    const elem = document.getElementById('image')
    const panzoom = Panzoom(elem, {
        canvas: false,
        cursor: 'move',
        maxScale: 4,
        minScale: 0.25,
        bounds: false,
        boundsPadding: 0.05,
        zoomDoubleClickSpeed: 1,
        zoomSpeed: 1,
        smoothScroll: false,
        smoothScrollSpeed: 1,
        smoothScrollStopDelay: 300,
        touchAction: 'none',
        touchEnabled: true,
        beforeWheel: function(e) {
            // allow wheel-zoom only if altKey is down. Otherwise - ignore
            var shouldIgnore = !e.altKey;
            return shouldIgnore;
        }
    })

    const zoomInButton = document.getElementById('image_zoom_in')
    zoomInButton.addEventListener('click', function(event) {
        panzoom.zoomIn()
    })
    const zoomOutButton = document.getElementById('image_zoom_out')
    zoomOutButton.addEventListener('click', function(event) {
        panzoom.zoomOut()
    })
    const resetButton = document.getElementById('image_zoom_reset')
    resetButton.addEventListener('click', function(event) {
        panzoom.reset()
    })

    {#const pasteButton = document.getElementById('image_paste_from_clipboard')#}
    {#pasteButton.addEventListener('click', function(event) {#}
    {#    // TODO: paste image from clipboard.#}
    {#    // See https://stackoverflow.com/questions/6333814/how-does-the-paste-image-from-clipboard-functionality-work-in-gmail-and-google-c#}
    {# }) #}

</script>

templates/index.html
{% extends "base.html" %}
{% block page %}

    {% if user.is_superuser %}
        <br>
        <a href="{% url 'GenomelEditor:admin_dashboard' %}">Admin dashboard</a>
    {% endif %}

    {% if user.is_authenticated %}
        <br>
        <a href="{% url 'GenomelEditor:annotate' %}">Annotate</a>
    {% endif %}

    {% include "annotator_dashboard.html" with sorted_annotator_stats=sorted_annotator_stats %}



{% endblock %}

templates/login.html
<form action="{% url 'GenomelEditor:login' %}" method="post">
    {% csrf_token %}
    <input class="login_form_input" type="text" name="username" placeholder="Username" required>
    <input class="login_form_input" type="password" name="password" placeholder="Password" required>
    <input class="login_form_input" type="submit" value="Login">
</form>

templates/volpiano_transcription.html
{% load static %}

<link type="text/css" rel="stylesheet" href="{% static 'volpiano_transcription.css' %}">

<div id="volpiano_transcription">
    <div id="volpiano_transcription_result">
        {# Here be the result of the transcription. The purpose of this field #}
        {# is to provide feedback: how does the current transcription look like? #}
        {# This will likely involve quite a bit of JavaScript. #}
    </div>
    <div id="volpiano_transcription_input">
{#        Here be the input field where the user edits the volpiano string.#}
        {# The important part is the form, which triggers updates to the Melody #}
        {# object in the database. #}
        <form action="{% url 'GenomelEditor:save_annotation' %}"
              id="volpiano_transcription_form"
              method="post">

            {% csrf_token %}
            <table id="volpiano_transcription_input_table">
                <tr>
                    <td>
                    <label id="volpiano_transcription_volpiano_input_label"
                           for="volpiano_transcription_volpiano_input">Volpiano</label>
                        <br>
                        <button id="volpiano_transcripition_volpiano_input_switch_font"
                                type="button">
                                {# Without setting the type, a button in a form always submits. #}
                            Show notes</button>

                    </td>
                    <td>
                    <textarea id="volpiano_transcription_volpiano_input"
                              form="volpiano_transcription_form"
                              name="volpiano"
                              rows="1"
                              cols="{{ melody.volpiano|length|add:"120" }}"
                    >{{ melody.volpiano }}</textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                    <label id="volpiano_transcription_syllabized_text_input_label"
                           for="volpiano_transcription_syllabized_text_input">Syllabized text</label>
                    </td><td>
                    <textarea id="volpiano_transcription_syllabized_text_input"
                              form="volpiano_transcription_form"
                              name="syllabized_text"
                              rows="1"
                              cols="{{ melody.syllabized_text|length|add:"40" }}"
                    >{{ melody.syllabized_text }}</textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                    <button id="volpiano_transcription_do_render"
                            type="button">
                        {# Without setting the type, a button in a form always submits. #}
                        Render
                    </button>
                    </td><td>
                    {# Here we render the current state of the transcription. #}
                    {# This requires quite a bit of javascripting (below). #}
                    <div id="volpiano_transcription_rendering_container">
                    </div>
                    </td>
                </tr>
            </table>

            <br>
            <label for="volpiano_transcription_is_adiastematic">Is adiastematic?</label>
            <input id="volpiano_transcription_is_adiastematic"
                   type="checkbox"
                   name="is_adiastematic"
                   value="{{ melody.is_adiastematic }}">
            <br>
            <label for="volpiano_transcription_is_incomplete_in_source">Is incomplete in source?</label>
            <input id="volpiano_transcription_is_incomplete_in_source"
                   type="checkbox"
                   name="is_incomplete_in_source"
                   value="{{ melody.is_incomplete_in_source }}">
            <br><br>

            <!-- State management. -->
            {% if melody.is_in_transcription %}
                <label for="volpiano_transcription_is_transcribed"><b>Is transcribed?<b></label>
                <input id="volpiano_transcription_is_transcribed"
                       type="checkbox"
                       name="is_transcribed"
                       value=true
                       {% if melody.show_as_transcribed %} checked {% endif %}
                >
            {% else %}
                <!-- TODO: see if user has permission to check?
                     At this point, the user should always have the permission to check,
                     because a melody that is already transcribed and requires checking
                     should never be selected for a user who does *not* have checking permissions.-->
                <label for="volpiano_transcription_is_checked"><b>Can be finalized?</b></label>
                <input id="volpiano_transcription_is_checked"
                       type="checkbox"
                       name="is_checked"
                       value=true
                       {% if melody.show_as_checked %} checked {% endif %}
                >
            {% endif %}
            <br>
            <input type="hidden" value="{{ chant.id }}" name="chant_id">
            <input type="hidden" value="{{ melody.id|default_if_none:"" }}" name="melody_id">
{#          <input type="hidden" value="{{ melody.timestamp }}" name="melody_timestamp">#}

            <input id="volpiano_transcription_form_submit" type="submit" value="Save">
        </form>
    </div>
</div>

<script type="application/javascript" src="{% static "scripts/volpiano_transcription_rendering.js" %}">
    // Provides the render() function that is attached to the "Render" button on clik in the following script.
</script>
<script type="application/javascript" id="volpiano_transcription_rendering_script">
    // This is for validation purposes.
    // When the user clicks the "Render" button, we want to render the current
    // state of the transcription into the div "volpiano_transcription_rendering_container".
    // We do this in the front-end by collecting the currently transcribed
    // melody and syllabized text in the form.
    const rendering_container = document.getElementById('volpiano_transcription_rendering_container');

    render_button = document.getElementById('volpiano_transcription_do_render');
    render_button.addEventListener('click', function(event) {
        const current_volpiano = document.getElementById('volpiano_transcription_volpiano_input').value;
        const current_syllabized_text = document.getElementById('volpiano_transcription_syllabized_text_input').value;
        console.log('Current volpiano: ', current_volpiano);
        console.log('Current syllabized text: ', current_syllabized_text);

        render(current_volpiano, current_syllabized_text, rendering_container);
    })
</script>
<script>
    // Swapping between showing the volpiano transcription as notes, in Volpiano font, and
    // as plain text.
    const show_notes_button = document.getElementById('volpiano_transcripition_volpiano_input_switch_font');
    const volpiano_input = document.getElementById('volpiano_transcription_volpiano_input');
    show_notes_button.addEventListener('click', function(event) {
        // Also change the button text between "Show notes" and "Show text".
        if (volpiano_input.style.fontFamily === 'Volpiano') {
            show_notes_button.innerHTML = 'Show notes';
            volpiano_input.style.fontFamily = 'monospace';
            // Change font size to 12px.
            volpiano_input.style.fontSize = '12pt';
        } else {
            show_notes_button.innerHTML = 'Show text';
            volpiano_input.style.fontFamily = 'Volpiano';
            // The notes are too small to read at 12pt, so we increase the font size to 16pt.
            volpiano_input.style.fontSize = '24pt';
        }
    })
</script>